import { Cell } from "../types";

export const initialBoard: Cell[][] = [
  [
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
  ],
  [
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
    { checker: null },
  ],
  [
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
    { checker: null },
    { checker: 'black' },
  ],

  [
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
  ],
  [
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
    { checker: null },
  ],
  [
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
  ],
  [
    { checker: null },
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
  ],
  [
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
    { checker: 'white' },
    { checker: null },
  ],
];
